trigger:
- master

steps:
- task: AzureFileCopy@2
  displayName: 'Copy template update to sandbox Azure blob storage $(storageSandbox)/$(ContainerName)'
  inputs:
    SourcePath: template
    azureSubscription: '$(azureSubscriptionSandbox)'
    Destination: AzureBlob
    storage: $(storageSandbox)
    ContainerName: $(ContainerName)
    BlobPrefix: arm/$(Build.Repository.Name)/$(Build.BuildNumber)